# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12ec31717f40bb7c698ad1e2d4c034c2be7c40a64e0b02f40ee023af8fd88a3860223180358be245f6e4565538761794d966b53b608a9ef1f9d7d2bec83d4720

test:
  secret_key_base: 388e90b7f48e72f8d124f26e4ffc764755f2539105089e5fcad15398a929a7dcd09b83f7c1d561b42c0f3470ebf149ca5a05018efc352d125dcdacc7750f973b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
